import re
from datetime import datetime

class CurriculumGenerator:
    """Generates personalized learning paths and content"""
    
    def __init__(self, hdam_system, researcher, rl_trainer):
        self.hdam = hdam_system
        self.researcher = researcher
        self.rl_trainer = rl_trainer
        self.user_profiles = {}
        
    def create_learning_path(self, user_id: str, target_skills: list) -> dict:
        """Generate a complete learning path for target skills"""
        if user_id not in self.user_profiles:
            self.user_profiles[user_id] = {
                'skills': {},
                'proficiency': 0.0,
                'engagement': 0.8,
                'time_spent': 0
            }
        
        learning_path = {
            'user_id': user_id,
            'target_skills': target_skills,
            'modules': [],
            'estimated_duration': 0,
            'generated_at': datetime.now().isoformat()
        }
        
        total_duration = 0
        for skill in target_skills:
            module = self._generate_module(skill, user_id)
            learning_path['modules'].append(module)
            total_duration += module['estimated_time']
            
        learning_path['estimated_duration'] = total_duration
        return learning_path
    
    def _generate_module(self, skill: str, user_id: str) -> dict:
        """Generate individual learning module for a skill"""
        # Research academic content
        papers = self.researcher.search_arxiv(skill, max_results=3)
        datasets = self.researcher.get_dataset_info(skill)
        
        # Create knowledge base for HDAM
        knowledge_facts = [paper['abstract'][:500] for paper in papers]
        # Safely access datasets
        ds_list = datasets.get(skill, [])
        knowledge_facts.extend([f"Dataset available: {ds}" for ds in ds_list[:2]])
        
        # Teach HDAM about this skill
        self.hdam.learn(knowledge_facts, verbose=False)
        
        # Generate lesson structure using HDAM reasoning
        lesson_plan_query = f"How to teach {skill} effectively to beginners?"
        lesson_plan_result = self.hdam.reason(lesson_plan_query, steps=100)
        
        module = {
            'skill': skill,
            'description': lesson_plan_result['result'][:200],
            'lessons': self._create_lessons(skill, papers),
            'quizzes': self._generate_quizzes(skill),
            'projects': self._suggest_projects(skill, datasets),
            'resources': [{'title': p['title'], 'url': p['url']} for p in papers],
            'estimated_time': len(papers) * 45 + 60,  # Minutes
            'difficulty': self._assess_difficulty(skill)
        }
        
        return module
    
    def _create_lessons(self, skill: str, papers: list) -> list:
        """Create structured lessons from research papers"""
        lessons = []
        for i, paper in enumerate(papers):
            lesson = {
                'id': f"{skill}_lesson_{i+1}",
                'title': f"Understanding {skill}: {paper['title'][:50]}...",
                'content': paper['abstract'],
                'key_concepts': self._extract_key_concepts(paper['abstract']),
                'duration': 45  # minutes
            }
            lessons.append(lesson)
        return lessons
    
    def _generate_quizzes(self, skill: str) -> list:
        """Generate adaptive quizzes using HDAM"""
        quiz_questions = []
        question_types = ['conceptual', 'application', 'analysis']
        
        for i, qtype in enumerate(question_types):
            query = f"Generate a {qtype} question about {skill}"
            result = self.hdam.reason(query, steps=50)
            
            quiz_questions.append({
                'id': f"{skill}_quiz_{i+1}",
                'type': qtype,
                'question': result['result'][:100],
                'options': [f"Option {j+1}" for j in range(4)],
                'correct_answer': 0,
                'explanation': "Explanation generated by HDAM"
            })
        
        return quiz_questions
    
    def _suggest_projects(self, skill: str, datasets: dict) -> list:
        """Suggest hands-on projects"""
        projects = []
        ds_list = datasets.get(skill, [])
        source_name = ds_list[0] if ds_list else 'public data'
        
        project_ideas = [
            f"Build a {skill} application using {source_name}",
            f"Analyze trends in {skill} research",
            f"Create a tutorial explaining {skill} concepts"
        ]
        
        for i, idea in enumerate(project_ideas):
            projects.append({
                'id': f"{skill}_project_{i+1}",
                'title': f"Hands-on Project: {idea.split(' ')[0]}",
                'description': idea,
                'difficulty': 'Intermediate',
                'estimated_hours': 8 + i*4
            })
        
        return projects
    
    def _extract_key_concepts(self, text: str) -> list:
        """Extract key concepts from text"""
        # Simple keyword extraction (would be more sophisticated in practice)
        words = re.findall(r'\b[A-Z][a-z]+\b', text)
        return list(set(words))[:5]
    
    def _assess_difficulty(self, skill: str) -> str:
        """Assess skill difficulty level"""
        complex_skills = ['quantum mechanics', 'advanced mathematics', 'machine learning']
        intermediate_skills = ['programming', 'statistics', 'data analysis']
        
        skill_lower = skill.lower()
        if any(cs in skill_lower for cs in complex_skills):
            return 'Advanced'
        elif any(is in skill_lower for is in intermediate_skills):
            return 'Intermediate'
        else:
            return 'Beginner'

